#!/usr/bin/env node
// Broker server. Reads a recipes JSON file (generated by the host launcher
// from sandbox-config.yaml), loads secrets from mounted env files, and runs
// only pre-approved recipes. Never returns raw secret values.

import { spawnSync } from "node:child_process";
import { cpSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import http from "node:http";
import os from "node:os";
import path from "node:path";
import process from "node:process";

const HOST = process.env.TEST_BROKER_HOST || "0.0.0.0";
const PORT = Number(process.env.TEST_BROKER_PORT || "8765");
const RECIPES_PATH = process.env.TEST_BROKER_RECIPES || "/broker/recipes.json";
const WORKSPACE_ROOT = process.env.TEST_BROKER_WORKSPACE || "/workspace";
const ENV_NAME_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/;

function loadConfig() {
  return JSON.parse(readFileSync(RECIPES_PATH, "utf8"));
}

function parseEnvFile(text) {
  const result = {};
  for (const rawLine of text.split(/\r?\n/)) {
    let line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    if (line.startsWith("export ")) line = line.slice(7).trimStart();

    const eq = line.indexOf("=");
    if (eq === -1) continue;

    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    } else {
      value = value.replace(/\s+#.*$/, "").trim();
    }
    if (ENV_NAME_PATTERN.test(key)) result[key] = value;
  }
  return result;
}

function loadSecretStore(config) {
  // config.secrets: { name: containerPath }
  const store = {};
  for (const [name, filePath] of Object.entries(config.secrets || {})) {
    try {
      const fileSecrets = parseEnvFile(readFileSync(filePath, "utf8"));
      // Tag every key with origin for selection
      for (const [k, v] of Object.entries(fileSecrets)) {
        store[k] = { value: v, source: name };
      }
    } catch (err) {
      console.error(`[broker] failed to read secret file ${filePath} (${name}): ${err.message}`);
    }
  }
  return store;
}

function selectSecrets(requested, store) {
  // requested: array of secret-bundle names ("app_env", ...) declared in recipe.
  // We return all env vars whose source matches one of the requested bundles.
  const env = {};
  if (!Array.isArray(requested)) return env;
  const wanted = new Set(requested);
  for (const [k, { value, source }] of Object.entries(store)) {
    if (wanted.has(source)) env[k] = value;
  }
  return env;
}

function redactText(text, secrets) {
  let out = text;
  for (const value of Object.values(secrets)) {
    if (typeof value === "string" && value.length > 0) {
      out = out.split(value).join("[REDACTED]");
    }
  }
  return out;
}

function splitLines(text) {
  return text.split(/\r?\n/).filter(Boolean);
}

function copyWorkspaceForRun() {
  // /workspace is mounted readonly in the broker (so the broker can never
  // mutate the agent's view of the repo). We copy to /tmp per recipe so
  // commands like `npm test` that write coverage/logs have somewhere to go.
  const dest = mkdtempSync(path.join(os.tmpdir(), "broker-run."));
  cpSync(WORKSPACE_ROOT, dest, { recursive: true });
  return dest;
}

function runRecipe(recipe, config) {
  if (!Array.isArray(recipe.command) || recipe.command.length === 0) {
    throw new Error("recipe command must be a non-empty argv array");
  }

  const store = loadSecretStore(config);
  const secrets = selectSecrets(recipe.secrets, store);

  const runDir = copyWorkspaceForRun();
  try {
    const [cmd, ...args] = recipe.command;
    const result = spawnSync(cmd, args, {
      cwd: runDir,
      env: {
        PATH: process.env.PATH,
        HOME: process.env.HOME,
        TMPDIR: process.env.TMPDIR || "/tmp",
        ...secrets,
      },
      encoding: "utf8",
      shell: false,
      timeout: (recipe.timeoutSec || 120) * 1000,
    });

    const stdout = redactText(result.stdout || "", secrets);
    const stderr = redactText(result.stderr || "", secrets);

    return {
      command: recipe.command,
      exitCode: result.status ?? 1,
      stdout: splitLines(stdout),
      stderr: splitLines(stderr),
      error: result.error ? result.error.message : undefined,
      timedOut: Boolean(result.error && result.error.code === "ETIMEDOUT"),
    };
  } finally {
    rmSync(runDir, { recursive: true, force: true });
  }
}

async function readJson(req) {
  const chunks = [];
  for await (const c of req) chunks.push(c);
  const body = Buffer.concat(chunks).toString("utf8");
  return body.trim() ? JSON.parse(body) : {};
}

function writeJson(res, status, payload) {
  const body = JSON.stringify(payload, null, 2);
  res.writeHead(status, {
    "content-type": "application/json",
    "content-length": Buffer.byteLength(body),
  });
  res.end(body);
}

const server = http.createServer(async (req, res) => {
  try {
    if (req.method === "GET" && req.url === "/health") {
      return writeJson(res, 200, { ok: true });
    }

    if (req.method === "GET" && req.url === "/recipes") {
      const config = loadConfig();
      // Expose names only — never command, never secret bundles.
      return writeJson(res, 200, { recipes: Object.keys(config.recipes || {}) });
    }

    if (req.method === "POST" && req.url === "/run") {
      let payload;
      try {
        payload = await readJson(req);
      } catch {
        return writeJson(res, 400, { error: "invalid JSON" });
      }

      if (Object.hasOwn(payload, "command")) {
        return writeJson(res, 400, { error: "arbitrary commands are not accepted" });
      }

      const name = payload.recipe;
      if (typeof name !== "string" || !/^[a-z][a-z0-9_-]*$/i.test(name)) {
        return writeJson(res, 400, { error: "invalid recipe name" });
      }

      const config = loadConfig();
      const recipe = (config.recipes || {})[name];
      if (!recipe) {
        return writeJson(res, 404, { error: `unknown recipe: ${name}` });
      }

      const result = runRecipe(recipe, config);
      return writeJson(res, 200, { recipe: name, accepted: true, ...result });
    }

    // Explicit deny endpoints — used by the verify script to prove the
    // broker won't leak raw secrets.
    if (req.url === "/raw-env" || req.url === "/secrets" || req.url === "/env") {
      return writeJson(res, 403, { error: "secret material is not exposed" });
    }

    writeJson(res, 404, { error: "not found" });
  } catch (err) {
    writeJson(res, 500, { error: err.message });
  }
});

server.listen(PORT, HOST, () => {
  console.log(`[broker] listening on http://${HOST}:${PORT}`);
  console.log(`[broker] recipes file: ${RECIPES_PATH}`);
});
